[package]
name = "test-icu"
version = "0.1.0"
authors = ["Christian Swinehart <drafting@samizdat.co>"]
edition = "2018"

[profile.release]
opt-level = 2
lto = "fat"
codegen-units = 1

[dependencies]

[dependencies.skia-safe]
version = "0.43.0"
features = ["textlayout"]